[package]
name = "async-usercalls"
version = "0.1.0"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"
edition = "2018"
description = """
An interface for asynchronous usercalls in SGX enclaves.

This is an SGX-only crate, you should compile it with the `x86_64-fortanix-unknown-sgx` target.
"""
repository = "https://github.com/fortanix/rust-sgx"
documentation = "https://edp.fortanix.com/docs/api/async_usercalls/"
homepage = "https://edp.fortanix.com/"
keywords = ["sgx", "async", "usercall"]
categories = ["asynchronous"]

[dependencies]
# Project dependencies
ipc-queue = { version = "0.1", path = "../ipc-queue" }
fortanix-sgx-abi = { version = "0.4", path = "../fortanix-sgx-abi" }

# External dependencies
lazy_static = "1.4.0"     # MIT/Apache-2.0
crossbeam-channel = "0.4" # MIT/Apache-2.0
fnv = "1.0"               # MIT/Apache-2.0

# For cargo test --target x86_64-fortanix-unknown-sgx
[package.metadata.fortanix-sgx]
threads = 128
