[package]
name = "tls"
version = "0.1.0"
authors = ["fortanix.com"]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4"
mbedtls = { version = ">=0.12.0, <0.14.0", default-features = false, features = ["std"] }
