[package]
name = "rust-sgx-ut"
version = "0.1.0"
authors = ["Fortanix, Inc."]
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
# Each data format lives in its own crate; the sample code below uses JSON
# but you may be using a different one.
serde_json = "1.0"
