[package]
name = "dcap-retrieve-pckid"
version = "0.2.1"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"
edition = "2018"
description = """
A retrieval tool for the SGX PCK ID that works with AESM.
"""
repository = "https://github.com/fortanix/rust-sgx"
homepage = "https://edp.fortanix.com/"
keywords = ["sgx", "dcap", "pck", "aesm", "aesmd"]
categories = ["command-line-utilities"]

[dependencies]
# Project dependencies
"aesm-client" = { version = "0.6.0", path = "../aesm-client", features = ["sgxs"] }
"dcap-ql" = { version = "0.5.0", path = "../dcap-ql", default-features = false }
"report-test" = { version = "0.4.0", path = "../report-test" }
"sgx-isa" = { version = "0.4.0", path = "../sgx-isa" }
"sgxs-loaders" = { version = "0.4.0", path = "../sgxs-loaders" }

# External dependencies
anyhow = "1.0"   # MIT/Apache-2.0
