[package]
name = "vme-pkix"
version = "0.1.1"
authors = ["Fortanix, Inc."]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/fortanix/rust-sgx"
description = "TLS Certificate encoding and decoding helpers for the Fortanix VME environment."
keywords = [ "certificate-handling", "sgx" ]
categories = ["cryptography"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
pkix = ">=0.1.0, <0.3.0"
