#!/bin/bash
#
# Copyright (c) Fortanix, Inc.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# ===================================================================
#
# Usage:
#   encrypt-ppid < ppid_hex > encppid_hex

wget -N https://certificates.trustedservices.intel.com/PPIDEncryptionPublicKey.pem
xxd -p -r | openssl pkeyutl -encrypt -pubin -inkey PPIDEncryptionPublicKey.pem -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256 -pkeyopt rsa_mgf1_md:sha256 | xxd -p -c 0
