[package]
name = "ias"
version = "0.1.2"
authors = ["Fortanix, Inc."]
license = "MPL-2.0"
edition = "2018"
description = "API definitions, tools, and client for the Intel Attestation Service."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { version = "0.13", optional = true }
bitflags = "1"
byteorder = "1.0"
log = "0.4"
percent-encoding = "2.1"
serde_bytes = "0.11"
serde-bytes-repr = { version = "0.1", optional = true }
serde_json = { version = "1", optional = true }
serde = { version = "1.0.7", features = ["derive"] }
url = "2.2"

mbedtls = { version = ">=0.8.0, <0.10.0", features = ["std"], default-features = false, optional = true }
pkix = "0.1"

sgx-isa = { version = "0.4", path = "../sgx-isa" }
sgx_pkix = { version = "0.2", path = "../sgx_pkix" }

[target.'cfg(not(target_env="sgx"))'.dependencies]
reqwest = { version = "0.11", features = ["json"], optional = true }

[features]
client = ["reqwest", "base64", "serde-bytes-repr", "serde_json"]
client-certificate = ["reqwest/native-tls"]

[dev-dependencies]
lazy_static = "1"
tokio = { version = "1", features = ["macros"] }
env_logger = "0.9.0"

[target.'cfg(not(target_env="sgx"))'.dev-dependencies]
clap = "2.23.3"

report-test = { version = "0.3", path = "../report-test" }
aesm-client = { version = "0.5", features = ["sgxs"], path = "../aesm-client" }
sgxs = { version = "0.7", path = "../sgxs" }
sgxs-loaders = { version = "0.3", path = "../sgxs-loaders" }

[[example]]
name = "attestation-tool"
required-features = ["client", "mbedtls"]
