# This workflow is used to build docker image for ppid-retrieval-tool

name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths:
      - "intel-sgx/ppid-retrieval-tool/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["master"]
    paths:
      - "intel-sgx/ppid-retrieval-tool/**"
      - ".github/workflows/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          persist-credentials: false

      - name: Build the Docker image
        run: |
          cd intel-sgx/ppid-retrieval-tool/Docker
          ./build.sh
